-- AlterTable
ALTER TABLE `product` ADD COLUMN `category` VARCHAR(191) NULL DEFAULT 'Geral',
    ADD COLUMN `costPrice` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `minStock` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `stockQuantity` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `unit` VARCHAR(191) NOT NULL DEFAULT 'UN';
